### ISSUE TITLE
Armor balancing

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#1]
1) Titanium Armor XL is 320 hp, games logic shows it should instead be 16 (tiles) X small titanium armor value X2 (size efficiency) for a total of 256 hp.
2) Living armor Needs an overhaul as regen doesn't scale with level making it very bad very quickly. Here are some ideas:
--More hp (Currently it's a 250 ly armor with less hp than even titanium). I'd suggest making it same value as Cobalt, without changing weight. An armor alternative to organic fuel. 
--Moving it to Jurgans tech tree, as it would have some niche use early on.
--Adding some zeros to the regen value so it's actually worthwhile at higher levels. 
3) Talonite/Decoy/Tungsten armor need overhaul of stats:
-- Decoy is from a 150 faction and goes the following in weight and hp:  22/120, 120/600 (**Should be 110 based on the 1x1 stats**), 270/1200. (**Should be 297/1080 based on 1x1 stats**)
-- Tungsten is also from a 150 faction and goes as such: 22/200, 100/800 (**Should be 110/800 based on stats of 1x1**), 252/1800 (**Should be 297/1800 based on 1x1 stats**)
-- Talonite comes in at the further distance of 250, which should suggest it ought to be the strongest of them all.  Stats are as follows: 20/200, 100/800, 270/1800. (**The 4x4 is 560/3200 but should be 640/3200 based on stats of 1x1**)
I propose making Talonite be based upon 20/120 ratio, Tungsten 22/200, and Decoy  30 hp with weight reaching a point it would only be more efficient than Talonite (Or, on par only?) when using apocalypse dampers.
4) Alternatively, I suggest making the armor from Ball, Fury and Electro become the equivalent of Cobalt, for resist armors: 2x res/special effect of vanilla ones for x1.8 weight and no health.

**Comment by GreyCardinal69** [comment]
Will look into this later today
