### ISSUE TITLE
Armor Balance #2

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#11]
This is keeping in mind the previous post, plus looking at endgame armors and this time tossing in shields as well. I only have 2x2 for rainbow so can't compare them properly. 
1. Vanilla, Cobalt and living armor are now in a good place. Based on 8/100, 16/180 and 16/100 respectively. Healing needs to be lowered on living (Plan was to be 1%/sec) for 1.9 if indeed it now scales which I've heard but can't confirm. 
2. Talonite stats are now consistent, based on 20/200. Worth noting the 4x4 resistance armors are objectively better than the non res 4x4 as they gain free stat. Tungsten 3x3 25% weight to resistance ones for balance so may be worth increasing heaviness here or lowering it for Tungsten.
3. Tungsten was never changed. Stats are still 22/200, 100/800, 252/1800. Considering they come from a much weaker faction (150 LY instead of 250) they should be worse than Talonite.  
4. Decoy stats are now consistent (Based on 22/120) but like Tungsten should be worse than Talonite. 
I propose keeping Tungsten based on 22/200, giving the 22/120 to Talonite and having Decoy fit the purpose of Ads ships with something along the lines of 30/450. 
5. Living armor is inconsistent. 1x1 stats are 15 hp, 2 EC, 100 weight. 2x2 is 100 hp, 8 EC, 400 weight. **(Should be 75 hp.)**. 3x3 is very overpowered. 360 hp, 27 EC, 900 weight. **(Should be 202.5 hp)**. Rather than nerfing too much the 1x1 can be buffed. To 25 for example. Possibly higher EC to balance but I'd suggest keeping weight 100. 

For the next three I suspect you'll change what the 1x1 stats are for 2x2 and 3x3 balance.

6. Meta-Void armor is inconsistent. 1x1 is 26hp, 35 res, 40 weight. 2x2 is 136 hp, 200 res/weight. **(Should be 130 hp, 175 res, 160 weight)** 3x3 is 315 hp, 900 res/weight. **(Should be 351 [maybe it was a typo?] hp, 472.5 res, 360 weight)**. 
7. Diffraction armor is inconsistent. 1x1 is 40 hp, 50 res/absorb, 100 weight. 2x2 is 260 hp, 512 res/absorb, 536 weight. **(Should be 200 hp, 250 res/absorb, 500 weight.) 3x3 is 495 hp, 1980 res/absorb, 1800 weight. **(Should be 540 hp, 675 res/absorb, 900 wight)**
8. Dissipation armor is inconsistent. Exactly same as Diffraction really. 1x1 is 40 hp, 50 ramming/res, 100 weight. 2x2 is 260 hp, 512 ramming/res, 536 weight. **(Should be 200 hp, 250 ramming/res, 500 weight)**.  3x3 is 495 hp, 1980 ramming/res, 1800 weight. **(Should be 540 hp, 675 ramming/res, 900 weight.)**

Shields honestly are pretty bad in this mod due to repair/leech weapons so I'd go so far as to say for a non-healing build they should be ***better*** than same-tier armor. Even more so as shield alternator is not worth giving up energy alt. Since Nerazim and Axis are same tier, I propose making Axis shields better on immobile builds for sheer tankiness and Nerazim coming with a good % recharge. Anyway, inconsistencies again: 

9. Exophase 1x1 is 1 EC, 30 shield points, 150 weight. 2x2 is 5 EC, 180 shield, 750 weight. **(Should be 150 shield, 600 weight)**. 3x3 is 13.5 EC, 486 shield, 1750 weight. **(Should be 405 shield, 1350 weight)**. I propose changing the 1x1 to be: No EC,and buffing shield to 60, and then raising weight to 450.
10. Templar shield 1x1 is 1.78 EC, 15 shield, 2.25 regen (effectively 1.5%) 50 weight.  2x2 is 7.11 EC, 90 shield, 11.25 regen, 200 weight. **(Should be 8.9 EC, 75 shield)** 3x3 is 16 EC, 243 shield, 36 regen and 450 weight. **(Should be 24 EC, 202.5 shield, 30 regen)**. I do see you counted tile number instead of compressed number for EC. 
Templar shield should be worse than Living armor so its trickier here to balance. Regardless I propose changing EC away from 1.78 (raise it to 2?) to make numbers more simple. I'm not sure where it should stand. A mix between Reactive and living armor pretty much. Worth noting vanilla shields are 50% hp at 40% weight and have no EC.

**Comment by GreyCardinal69** [comment]
Will do eventually .

**Comment by GreyCardinal69** [comment]
Did Most
