### ISSUE TITLE
Unnecessary blueprints

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#12]
Disclaimer, this is somewhat speculation on my part.

1) Free Star tree still have the large shield and shield regen modules hidden. I can understand all the ships being BP locked but not those.
2) Veneri tree has big drone bay, and boost module locked leftover from vanilla. I don't know if either are suddenly super strong, but suspect they shouldn't be hidden.

**Comment by Nsyion** [comment]
Bushrak large drones and drone module are also hidden.  Is it better if in the future I edit OP are add comment for further ino?

**Comment by GreyCardinal69** [comment]
> 1. Free Star tree still have the large shield and shield regen modules hidden. I can understand all the ships being BP locked but not those. Hid those.

> Veneri tree has big drone bay, and boost module locked leftover from vanilla. I don't know if either are suddenly super strong, but suspect they shouldn't be hidden. That too

> Bushrak large drones and drone module are also hidden. Is it better if in the future I edit OP are add comment for further ino?
 I'll unhide em soon.

**Comment by Nsyion** [comment]
You didn't reply if I should edit or add new comments when I have further to add.

Korerans also have unnecessary BP (Can only list factions as I re-find them). 
Surely EMP torp, large repair bot and Large drone factory aren't so strong they need exploration..

**Comment by GreyCardinal69** [comment]
> 
> 
> You didn't reply if I should edit or add new comments when I have further to add.
> 
> Korerans also have unnecessary BP (Can only list factions as I re-find them).
> Surely EMP torp, large repair bot and Large drone factory aren't so strong they need exploration..

Write all.

**Comment by Nsyion** [comment]
> Write all.

 👍 

HLBM2, Acid Missile - Jurgans
Machinegun, singularity cannon - Neganari (Imo 3x3 damper being hidden is good)
HAMBM2, Large Drone Bay, Large Drone booster - Taraniak 

I'm more than happy to debate what is worth hiding behind a BP or not if you disagree and are willing to discuss.

**Comment by GreyCardinal69** [comment]
Unhid all mentioned.
