### ISSUE TITLE
Veniri Faction

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#14]
I'm sure more will be added, but for now:
1) Pulse cannon is 50% bigger than small pulse m2 and locked to C slots but is barely better. 2.3 dmg instead of 2.2, and 23 range, 24 velocity vs 20/20.
I propose making it 3 damage, 25/25.

2) Pulse cannon M2
14.4 dps to m1's 11.5. But also using 10 EC vs 5. Its been terrible since vanilla and hasn't improved much. (24/25 R/V btw)

Keeping in spirit of the original design I'd keep the lower rof, but perhaps buff either R or V to 30, and lower EC some. Say, to 2.5 or 3.

**Comment by Nsyion** [comment]
Is it better if I make topics per faction, or module type?

**Comment by GreyCardinal69** [comment]
faction

**Comment by Nsyion** [comment]
Heavy Pulse Cannon is underpowered due to poor damage efficiency. For 1x5 C, 21 dps for 15 eps just isn't worth using. 

While it loses in range (which isn't even a big deal due to velocity on pulse) , a  Neutron Cannon will be outputting a similiar 20 dps, for only 4 eps and in 1x3 slots. 

At the very least I'd suggest dropping EC to 2 or even dropping it down to 1. Velocity and range seem fine. Buffing damage would also work.

**Comment by GreyCardinal69** [comment]
Buffed heavy pulse cannon, EC is 1 now, also buffed damage.
