### ISSUE TITLE
Armada Faction

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#17]
Tech tree seems a mess: Unnecessary  hidden BP, and oddly high tech costs for drone bays.

**Comment by Nsyion** [comment]
1) E-7 Guardian is a 282 slot Cruiser that is a prerequisite to an unremarkable E-13 Interceptor 94 slot frigate surely should be swapped?

2) HY-17 is a 367 slot battleship, and yet it comes before HY-22-85 an 83 slot Destroyer which comes before HY-24-B, a 314 slot Battler ship.
HY-22 and HY-17 should probably be swapped?
Or even, have them go in order of smallest to biggest. HY-22 then HY-24 and only then HY-17?

3) Also worth noting is their CS is a fairly small 634 slots. 

To preserve order of numbers, ship names can also be swapped around.

**Comment by GreyCardinal69** [comment]
Fixed the tech cost and the hidden blueprints, not sure about order, it came like that from Noodle himself iirc.
