### ISSUE TITLE
Zumbalari Faction

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#19]
Neutron Blasters don't scale well, yet another problem leftover from vanilla I feel like may as well be addressed.

(dmg, ec, rof, range, velocity)
* Basic is 5/1/4/20/20 1x3 slots
* M2 is 7/3/4/25/22 1x4
* Heavy is 9/3/5/24/22 2x3

M2 and Heavy are bigger and yet lose efficiency. They don't gain enough dps/range/velocity imo to justify using them.
I propose:
* M2 5/1/5/25/25 
* Heavy 10/2/5/30/30

**Comment by GreyCardinal69** [comment]
Changed to proposed values.
