### ISSUE TITLE
Missing Starbase

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#20]
Opening issue as I suspect more lack.

Syndicate

**Comment by Nsyion** [comment]
Corporation

**Comment by GreyCardinal69** [comment]
Added builds for both factions.

**Comment by Nsyion** [comment]
Reopen plz.
Balls
Korgar
Mekror      
Arkys
Ignotis
Dominion

Fully expecting to find more

**Comment by Nsyion** [comment]
Marauders

**Comment by GreyCardinal69** [comment]
Fixed
