### ISSUE TITLE
Corporation Faction

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#21]
Small Disruptor Ray m2 is worse (imo) when compared to basic.

Small is 1x2 C, 7.5 dmg, 5 ec, 1 rof, 13 range and 30 velocity.
for +50% more space, the 1x3 (m2) gains 2.5 dmg  and 2 range at the cost of gaining 3 ec.

I suggest lowering the EC to 6.5 or upping damage to 12. to maintain roughly the same 1.5/1 efficiency of m1.

That being said, none of the C weapons seem worth using as the should-be-available-much-earlier neutron weapons are better.

**Comment by Nsyion** [comment]
Large drone bay is behind BP, should be swapped with the Battleship?

Also, Gladius Driver M2 isn't worth using.
Basic is 2x3, 90 damage, 60 EC, 0.2 rof, 47.5 range, 20 velocity, 5 aoe.

m2 is 2x4, damages goes up to 120 and aoe to 5.5, but EC also goes up to 105.
Its bigger, and less efficient. Doesn't even make up for it with better range or something.

**Comment by GreyCardinal69** [comment]
Did some of the suggestions.
