### ISSUE TITLE
Mekror Faction

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#24]
Again ships are all BP. Is this leftover from RBE?

Can't confirm yet but pretty sure overheat module, and shield alternator are both useless.

**Comment by Nsyion** [comment]
Happy to find Shield Alt no longer interferes with Energy Alt, making it useful for midgame. 
I did notice there's an inconstancy however. Shield says "Recharge Rate -10" and Energy says "Energy Consumption 10".

Overheat still terrible. I propose the following to limit its power but make it more useful:
* 20 regen instead of 30 (making it on par with Organic). Instead of adding cooldown, it would add EC like in RBE (50%?) **and** be  heavier. I'm thinking 400 mass.
* Idea is "A very good reactors for slow/immobile, drone-only carriers" As drones anyway become bad by 200-250 ly. Weight limits its use on faster ships, EC is a big drawback for things using guns.
* Downside is, any build currently using it (I mean AI, not player) will need changing to account for the new stats.

**Comment by GreyCardinal69** [comment]
No longer hidden bps, change overheat to proposed stats, will think about drone carrier specialized reactors.
