### ISSUE TITLE
Ignotoniants Faction

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#27]
From my testing (hard to be certain when I can't see true numbers ingame): 
1x3 Cumulative Cannon is better than the *later* unlock Cumulative Cannon m2.
Both are same size, and from my testing have identical range/velocity.
However m1 is dealing 37.5 dps for 7.5 eps. m2 is only dealing 32, and for a much higher 14.

If not wanting to mess with dps stuff so as to keep the 1x3 m2 in line with later unlocks, at least it could get a much lower EC and/or better range.

**Comment by GreyCardinal69** [comment]
lowered EC Of m2 and increased its range
