### ISSUE TITLE
Marauders Faction

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#28]
1) V weapons are limiting for both player and AI builds. Imo the ships and modules alike aren't strong enough to warrant a special slot type. I propose making them C/M/L. 
2) Is there a reason void dampers aren't on the tree yet? Even post-CS would still be better than looted only. Missile and rocket aren't on the tree either.

I recall the other guns not being great, but at least have the Void Radiant Cannon in front of me to comment on.
If not for EC, itd be a solid weapon. I propose lowering it to 4:1. dps is plenty so wouldnt buff that instead.

**Comment by GreyCardinal69** [comment]
Change ships' slots to cml, void radiant cannon has 10 EC instead of 20 now, S,M void dampers as well as the Redeemer missile are now available in the tech tree.
