### ISSUE TITLE
Armored Accumlator is overpowered

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#6]
Much as I hate to admit it, it currently has 3x size efficiency for the mere cost of 1.05x weight. 

Furthermore, this is craftable, and from an earlier distance faction than the advanced nuclear reactor and Pressurized fuel part of it is based on. It can also be placed on green slots.
Currently pretty much hand down is the best armor/fuel from 70 lightyear until at least apocalypse tier. I'm not certain of exact numbers but propose making it be x2 current weight as a start.

**Comment by GreyCardinal69** [comment]
.
