### ISSUE TITLE
Living Armor crafting issue

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#8]
I noticed that they can only get -weight as a modifier, and not more defense or repair rate. Also I've noticed that all 3 sizes of it cost the same amount to craft upgraded. (At least tech star wise, didn't pay attention to credits)

**Comment by juh9870** [comment]
Repair rate upgrade does nothing for components giving HP regen.
Will add defence modifier in next fix

**Comment by GreyCardinal69** [comment]
Added Defense Modifier
