### ISSUE TITLE
Upgrade options on hidden items, plus spark upgrades

### ISSUE THREAD

**Issue by Nsyion** [juh9870/EoP_releases#9]
I've always thought the "-weight" modifier only existed so that people can find +weight grey items instead of say,  "extra-early" modules found having -energy% -damage% ect.

As such, in a somewhat drastic move I would like to propose any module that can't be bought (such as apoc reactors, ghost plasma missile) have the -weight modifier removed as an option. It just serves to waste time and the mod already is long enough.

I would like to propose for sparks, giving the following options as they currently can't get upgrades but will still happily use up one's tech if they try it:
Spark of Speed: engine power.
Spark of Power: -weight
Spark of Defense: -weight as an option or +defense.

**Comment by GreyCardinal69** [comment]
hmst

**Comment by GreyCardinal69** [comment]
will do later
